<?php

/**
 * This file is automatically generated. Use 'bin/celerity map' to rebuild it.
 *
 * @generated
 */
return array(
  'names' => array(
    'sourcegraph-config.js' => '37cc69ab',
    'sourcegraph.js' => '15f5c477',
  ),
  'symbols' => array(
    'javelin-behavior-sourcegraph-config' => '37cc69ab',
    'sourcegraph' => '15f5c477',
  ),
  'requires' => array(),
  'packages' => array(),
);