<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'CeleritySourcegraphResources' => 'celerity/CeleritySourcegraphResources.php',
    'PhabricatorSourcegraphConfigOptions' => 'config/SourcegraphConfigOptions.php',
    'SourcegraphApplication' => 'application/SourcegraphApplication.php',
    'SourcegraphConduitAPIMethod' => 'conduit/SourcegraphConduitAPI.php',
  ),
  'function' => array(),
  'xmap' => array(
    'CeleritySourcegraphResources' => 'CelerityResourcesOnDisk',
    'PhabricatorSourcegraphConfigOptions' => 'PhabricatorApplicationConfigOptions',
    'SourcegraphApplication' => 'PhabricatorApplication',
    'SourcegraphConduitAPIMethod' => 'PhabricatorAuthConduitAPIMethod',
  ),
));